fc_input = 8
latent_dim = 128
bias = true

[block]
kernel_size = 4
stride = 2
padding = 1
bias = true

[leaky_relu]
negative_slope = 0.2

[enc]
channels = [1, 32, 64, 128, 256]

[dec]
channels = [256, 128, 64, 32, 1]