fc_input = 16
fc_output = 128
latent_dim = 128
bias = false

[block]
kernel_size = 4
stride = 2
padding = 1
#dilation = 1
#bias = false

[enc]
channels = [32, 64, 128]

[dec]
channels = [128, 64, 32]

[up_conv]
kernel_size = 4
stride = 2
padding = 1

[head]
kernel_size = 3
padding = "same"