fc_input = 16
latent_dim = 128
bias = true

[block]
kernel_size = 4
stride = 2
padding = 1
bias = true

[leaky_relu]
negative_slope = 0.2

[enc]
channels = [1, 32, 64, 128]

[dec]
channels = [128, 64, 32, 1]

[head]
kernel_size = 3
stride = 2
padding = 1
output_padding = 1
bias = true

