fc_input = 8
fc_output = 512
latent_dim = 256
bias = true

[block]
kernel_size = 3
stride = 1
padding = 1
bias = false

[enc]
channels = [1, 32, 64, 128, 256, 1024]

[dec]
channels = [1024, 256, 128, 64, 32, 1]

[up_conv]
kernel_size = 2
stride = 2

[head]
kernel_size = 3
stride = 1
padding = 1
bias = true

[pool]
kernel_size = 2
stride = 2