[model]
input_dim = 128
latent_dim = 512

[optimizer]
lr = 0.0005
betas = [0.5, 0.999]
weight_decay = 1e-5

[train_loader]
brains = ["B01", "B02", "B05"]
tile_size = 128
batch_size = 128
tiles_per_epoch = 2000
num_workers = 0

[val_loader]
brains = ["B07"]
tile_size = 128
batch_size = 128
tiles_per_epoch = 1000
num_workers = 0

[trainer]
num_epochs = 5