[model]
input_dim = 64
latent_dim = 128

[optimizer]
lr = 3e-4
weight_decay = 0.01

[train_loader]
brains = ["B01", "B02", "B05"]
tile_size = 64
batch_size = 16
tiles_per_epoch = 1000
num_workers = 0

[val_loader]
brains = ["B07"]
tile_size = 64
batch_size = 16
tiles_per_epoch = 100
num_workers = 0

[trainer]
num_epochs = 10