# [model]
# input_dim = 128
# latent_dim = 256


[model_mashood]
input_dim=128
last_hidden_dim=128
encoder_channels=[1, 32, 64, 128]
decoder_channels=[128, 64, 32, 1]

[loss]
beta = 1.0

[optimizer]
lr = 3e-4
# betas = [0.5, 0.999]
# weight_decay = 1e-5

[train_loader]
brains = ["B01", "B02", "B05"]
tile_size = 128
batch_size = 16
tiles_per_epoch = 10000
num_workers = 0

[val_loader]
brains = ["B07"]
tile_size = 128
batch_size = 16
tiles_per_epoch = 100
num_workers = 0

[trainer]
num_epochs = 20
