[model]
input_dim = 256
latent_dim = 256

[optimizer]
lr = 0.001
weight_decay = 1e-7

[train_loader]
brains = ["B01", "B02", "B05"]
tile_size = 256
batch_size = 32
tiles_per_epoch = 2000
num_workers = 0

[val_loader]
brains = ["B07"]
tile_size = 256
batch_size = 32
tiles_per_epoch = 100
num_workers = 0

[trainer]
num_epochs = 5